#prefix used to show metrics in all tiers (NOT RECOMMENDED)
#metricPrefix: "Custom Metrics|LogMonitor|"

# metric prefix to show metrics in one tier (HIGHLY RECOMMENDED)
# Please follow the Metric Path section of https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java for instructions on retrieving the tier ID

metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Log Monitor|"

logs:
  - displayName: "TESTING"
    logDirectory: "/Users/aj89/Documents/LogMonitorTesting"
    logName: "server.log"
    encoding: ""      #Not mandatory. Supported types: UTF8, UTF16, UTF16-LE, UTF16-BE, UTF32, UTF-32LE, UTF32-BE
    searchStrings:
        #displayName Should be unique across the various patterns.
       - displayName: "Info Statements"
         pattern: "INFO"
         matchExactString: true
         caseSensitive: true
         printMatchedString: false

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
    - replace: ":"
      replaceWith: ";"
    - replace: "\\|"
      replaceWith: "#"
    - replace: "\\,"
      replaceWith: "#"

# Number of concurrent threads
numberOfThreads: 20

#Thread timeout in seconds
threadTimeOut: 60

sendDataToEventsService: false

logMatchOffset: 5

# This field contains the various parameters required to initiate a connection and send data to the AppDynamics Events Service.
eventsServiceParameters:
  host: ""
  port: 9080
  globalAccountName: ""
  eventsApiKey: ""
  useSsl: false
